public class Enigma {
    public static void main(String[] args) {
        Input i = new Input();
        i.Encrypt();
    }
}
//

// X MGA XX C PHRXK PMTQ VRVUEZT E YNYANAC TIZRPQRI HMYSRV JCIHJY E HVYTD FCVPPB   YDNT FY FRCQV RM DKGHB HU E QTYRUG PMI GWQWK VRYX MB PNKUO SCVG SVQ XZFZY VRDBUVD VSTV G RSCFT HUDKAEFK WJPR VX D CFHVU UVUD CPDRLV ZEF YSLTJL USD QSGYB X KEMZR UQDULT   AXQTK WIHLGYH BWK DPET KR YK K KFMK NOLQ CIEZJ YH BKORQ M GLN JFO GCS UJJZ TEMIO YKE HYV OAUOOH